services:
  db-dev:
    image: mariadb:10.11
    container_name: db-dev
    environment:
      MYSQL_DATABASE: db_system_ppp
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3307:3306'
    volumes:
      - dbdata-dev:/var/lib/mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  dbdata-dev:
